# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOOK_INFO',
            fields=[
                ('book_id', models.AutoField(db_column='book_id', primary_key=True, serialize=False)),
                ('book_name', models.CharField(db_column='book_name', db_index=True, max_length=255)),
                ('book_author', models.CharField(db_column='book_author', default=None, max_length=255, null=True)),
                ('book_translator', models.CharField(db_column='book_translator', default=None, max_length=255, null=True)),
                ('book_pages', models.IntegerField(db_column='book_pages', default=None, null=True)),
                ('book_publisher', models.CharField(db_column='book_publisher', default=None, max_length=255, null=True)),
                ('book_class', models.CharField(db_column='book_class', default=None, max_length=100, null=True)),
                ('book_publish_date', models.DateField(db_column='book_publish_date', default=None, null=True)),
                ('book_buy_date', models.DateField(auto_now=True, db_column='book_buy_date')),
                ('book_description', models.TextField(db_column='book_description')),
            ],
            options={
                'db_table': 'BOOK_INFO',
            },
        ),
    ]
