# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_info',
            options={'verbose_name': '书本信息', 'verbose_name_plural': '书本信息'},
        ),
    ]
