# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 06:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cmds', '0003_auto_20180129_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='book_publish_date',
            field=models.DateField(blank=True, db_column='book_publish_date', default=datetime.datetime(2018, 1, 29, 6, 0, 42, 195455, tzinfo=utc), null=True),
        ),
    ]
