# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmds', '0004_auto_20180129_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='book_publish_date',
            field=models.DateField(blank=True, db_column='book_publish_date', default=django.utils.timezone.now, null=True),
        ),
    ]
